[build]
  command = "npm run build"
  publish = "client/dist" # Specify the Angular build output directory

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[functions]]
  directory = "server" # Specify the directory where serverless functions are located
